version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 14
  
  pre_build:
    commands:
      - npm install
  
  build:
    commands:
      - node --version
      - npm run build
  
  post_build:
    commands:
      - npm run sonar-scanner -DprojectName=bizbazaar-frontend -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey=bizbazaar_bizbazaar-frontend -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${SONAR_TOKEN}

artifacts:
  files:
    - Dockerfile
    - build/**/*
    - nginx/nginx.conf