version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 14
    commands:
      - npm install -g sonarqube-scanner
  
  pre_build:
    commands:
      - npm install
  
  build:
    commands:
      - node --version
      - npm run build
  
  post_build:
    commands:
      - sonar-scanner -DprojectName=bizbazaar-frontend -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=bizbazaar -Dsonar.projectKey=bizbazaar_bizbazaar-frontend -Dsonar.host.url=https://sonarcloud.io/

artifacts:
  files:
    - Dockerfile
    - build/**/*
    - nginx/nginx.conf